#------Pages
home:
  path: /
  controller: App\Controller\SiteController::index

new:
  path: /new
  controller: App\Controller\SiteController::newTrack

#----- Links for Track
upload_file:
  path: /tracks/upload
  controller: App\Controller\TrackController::uploadFile

download_file:
  path: /tracks/download/{fileID}
  controller: App\Controller\TrackController::downloadFile

update_file:
  path: /tracks/update/{fileID}
  controller: App\Controller\TrackController::updateFileInfo

delete_file:
  path: /tracks/delete/{fileID}
  controller: App\Controller\TrackController::deleteFile

tracks:
  path: /tracks
  controller: App\Controller\TrackController::getTracksList

track_id:
  path: /tracks/{ID}
  controller: App\Controller\TrackController::getTrackByID

# ----- Links for Tag
tags:
  path: /tags
  controller: App\Controller\TagController::getTagsList

add_new_tag:
  path: /tags/add
  controller: App\Controller\TagController::addNewTrack

delete_tag:
  path: /tags/delete/{tagID}
  controller: App\Controller\TagController::deleteTag

update_tag:
  path: /tags/update/{tagID}
  controller: App\Controller\TagController::updateTag

categories:
  path: /tags/categories
  controller: App\Controller\TagController::getCategories

# ------------- Links for Employee
employees:
  path: /employees
  controller: App\Controller\EmployeeController::getEmployees

employee_add:
  path: /employees/add
  controller: App\Controller\EmployeeController::addEmployee

employee_update:
  path: /employees/{ID}/update
  controller: App\Controller\EmployeeController::updateEmployeeInfo

employee_delete:
  path: /employees/{ID}/delete
  controller: App\Controller\EmployeeController::deleteEmployee

upload_employee_photo:
  path: /employees/{ID}/photo/update
  controller: App\Controller\EmployeeController::uploadImage

employee_photo:
  path: /employees/{ID}/photo
  controller: App\Controller\EmployeeController::downloadImage

# ------------- Links for Subdivisions
subdivisions:
  path: /subdivisions
  controller: App\Controller\SubdivisionController::getSubdivisionsAndPosts

subdivision_add:
  path: /subdivisions/sub/add
  controller: App\Controller\SubdivisionController::addSubdivision

subdivision_update:
  path: /subdivisions/sub/{ID}/update
  controller: App\Controller\SubdivisionController::updateSubdivision

subdivision_delete:
  path: /subdivisions/sub/{ID}/delete
  controller: App\Controller\SubdivisionController::deleteSubdivision
